### ISSUE TITLE
Dockerize Tideflow [$15]

### ISSUE THREAD

**Issue by joseconstela** [tideflow-io/tideflow#50]
The idea is to make Tideflow to run on docker containers for production environment, so that anyone can easily run it.

For this, we want to create:
- A docker file that builds, runs and makes the application accesible.
- A docker-compose file that takes care of launching both the application and the database.

The files MUST:
1. Use the latest NodeJS and MongoDB compatible & supported versions with MeteorJS 1.8.1.
2. Create safe-networking environment configuration between the application and the database (so the database is only accesible by Meteor).

Additional Networking requirements:
- Exposed ports includes 80 & 1337 (for SocketIO server)

---

Link to current deploying docummentation https://docs.tideflow.io/docs/deploying

**Comment by Jean-Baptiste-Lasselle** [comment]
hi @joseconstela , is [the bounty](https://www.bountysource.com/issues/83428377-dockerize-tideflow) still open ?

**Comment by joseconstela** [comment]
Hello @Jean-Baptiste-Lasselle ! Yes it's !

**Comment by joseconstela** [comment]
I've update the issue description with additional networking requirements. (Exposed ports includes 80 & 1337 (for SocketIO server))
