### ISSUE TITLE
[ISSUE] PDF downloaded files are blank [$15]

### ISSUE THREAD

**Issue by joseconstela** [tideflow-io/tideflow#65]
PDF downloaded files are blank, even if they are created correctly. The problem seems to be on the MongoDB GFS storage or download process. 

If you create a workflow that generates a PDF from a template, to send it via email and to store the file, the email PDF is correct, but the stored copy is blank. See:

[pdf-from-the-email.pdf](https://github.com/tideflow-io/tideflow/files/3964019/pdf-from-the-email.pdf)
[pdf-stored-in-gfs.pdf](https://github.com/tideflow-io/tideflow/files/3964020/pdf-stored-in-gfs.pdf)

## Steps to reproduce

1. **Create an HTML file to be used as a PDF template.** 
   - Files => New File ... => Basic HTML Structure
2. **Create a new workflow that generates a PDF from the template, and stores the file**
   - Trigger: When an endpoint is reached
   - PDF: Create from HTML
   - Files: Store previous files
3. **Trigger the flow** 

**Result:** The new file, accesible via the "Files" section, in an empty PDF file. 57KB. Whatever software is used to open the PDF file, this is blank.

**Expected result:** The downloaded file is PDF that contains the html's template body.

## Affected branch

[pdf-downloaded-blank](https://github.com/tideflow-io/tideflow/tree/pdf-downloaded-blank)

---

video https://www.youtube.com/watch?v=uvObbcyeaOw

**Comment by tomHaum** [comment]
So it looks like you are double saving the files, is the `Files` mongo collection for metadata about the files and the `attachments` bucket is for blob storage?

**Comment by joseconstela** [comment]
That's correct. `files` collection stores metadata, and the references to the files in the `attachments` collection. 

<img width="964" alt="Captura de pantalla 2019-12-17 a las 19 20 28" src="https://user-images.githubusercontent.com/6388629/71023270-b1829e00-2102-11ea-8b90-06e01d23dbb8.png">

**Comment by joseconstela** [comment]
Problem was that download are made via BLOB urls. This is not fixed and will be released soon
